### ISSUE TITLE
Indentation not correct

### ISSUE THREAD

**Issue by Paultje52** [ecmel/prettier-plugin-ejs#6]
In one of my EJS files, I have the following content.
```ejs
<% components.forEach((component) => { %>
  <% if (component.type === "TEXT") { %>
    <h1><%- component.parsedContent %></h1>
  <% } %>
<% }); %>
```
I expect this plugin to keep these indentations for readability (just like if they were HTML elements), but this plugin removes all the indendations (see code block below).
```ejs
<% components.forEach((component) => { %>
<% if (component.type === "TEXT") { %>
<h1><%- component.parsedContent %></h1>
<% } %>
<% }) %>
```
This makes larger EJS files unreadable, which isn't desired.

**Comment by ecmel** [comment]
The plugin just marks the ejs comments as html comments. All the indentation is for html. This has pros and cons but want to keep this extension simple.

**Comment by Paultje52** [comment]
Is there another way to use the right indentation?

**Comment by ecmel** [comment]
Currently, the document is formatted as html and not js.
